### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by uyiOriaghan** [axcl/SMACK-API-Android-Demo#1]
Hello axcl, i really appreciate this demo it saved my day. when are some more feature gonna be added, features like getting and setting presence, message delivery report and other important requirements for a standard IM.
Thanks so much
oriaghan3@gmail.com

**Comment by axcl** [comment]
Glad! that i can help you.. sorry i am too much busy so i can not devote much time to this project...but it will be great help if you can help me to extend some features.

**Comment by uyiOriaghan** [comment]
sure that will be great, as i move on with the project i will extend it. but i gat one quick question, when i try to use the "sendMsg(String message, String recipient)" it tells me that "connection" (i.e the object of AbstractXMPPConnection) is null, i get confused because i believe it get created when i call the sign in function. please help this is really important if i am gonna be able to move on with the project. thanks
