### ISSUE TITLE
Please Provide a user name and password so that i can test whole app.

### ISSUE THREAD

**Issue by anki1427** [axcl/SMACK-API-Android-Demo#2]
Hello,
Please provide me the username and password with your server Nimbuzz so that i can use that user to test the demo app

**Comment by axcl** [comment]
Hi Ankita,

Nimbuzz is free service.. you can register an account through their app. Or
you can jabber.org

**Comment by axcl** [comment]
Use*

**Comment by axcl** [comment]
Closing the issue cause no further response
